### PR TITLE
Fix issue #4, make some goto cases work as expected

### PR DESCRIPTION
**Pull request by z4139jq**
Fix goto-value in cases:
* it is a absolute path **without suffix**, try to locate it with .js or .jsx suffixes
* it is a relative path, make it absolute to avoid relying on the current dir be the project root, so that it is feasible to restore the default-directory after calling importjs to fix issue #4

Given this dir layout:
```
  App.js
  configureStore.js
  components/
  ├── EbookPage.js
  ├── MePage.js
  ├── QuestionPage.js
  └── TabIcon.js
  containers/
  └── Root.js
  actions/
  └── ebooks.js
  reducers/
  ├── ebooks.js
  └── index.js
```
So that cases below should **work as expected**:
* `import EbookList from './components/EbookPage'` in App.js, goto EbookList, components/EbookPage.js opened
* `import { fetchEbooks } from '../actions/ebooks'` in components/EbookPage.js, goto fetchEbooks, actions/ebooks.js opened
* `import rootReducer from './reducers'` in configureStore.js, goto rootReducer, reducers/index.js opened

### CODE REVIEW

**Comment by kevinkehl** [comment]
@z4139jq ah, I think I see the issue here now, goto isn't working with named exports, I've reproduced.

With this change, I'm still not able to use `goto` when my project root (where the .importjs.js config sits) is not the root of my code:

```
  namedExports: {
    'constants/app_constants': [
      'Actions',
    ],
  },
  lookupPaths: [
    'app',
  ],

```
with the following structure:

```
  .importjs.js
  app/
  └── MyComponent.js
  └── constants/
      └── app_constants.js
```

and I am using something like:

`import { Actions } from 'constants/app_constants';`

Using `goto` on `Actions` opens `constants/app_constants` from the root directory, where it should be `app/constants/app_constants`.

@trotzig @lencioni this issue probably also appears in other editors, could it be a base import-js issue?

**Comment by z4139jq** [comment]
@kevinkehl , with your dir layout and `.importjs.js` config, tested using importjs outside Emacs:
```
~/tmp/ipjs$ importjs goto Actions app/MyComponent.js |pj
{
  "messages": [

  ],
  "fileContent": "// MyComponent\nimport { Actions } from 'constants/app_constants';\n",
  "unresolvedImports": {
  },
  "goto": "/Users/zhujunqi/tmp/ipjs/constants/app_constants"
}
```
We can see that **importjs gives us the wrong `goto` path**.

**Comment by trotzig** [comment]
Thanks @z4139jq for making me aware of this issue. And apologies for the late response, I've been out traveling for a few days. 

I've managed to reproduce this in the core import-js project, and I've pushed a patch release to fix it. Can you try updating to v 1.1.2 and try this again? For reference, here's the commit that fixes things: https://github.com/Galooshi/import-js/commit/510e3a190e2680d40fb17c79e403d9d7e6872c78

The bug would happen when trying to `goto` a variable defined in a `namedExport`. We didn't properly resolve the path, and as a result the file ending was missing. 

@kevinkehl: I believe your config is slightly incorrect. Named exports need full paths (including lookup path), so your `namedExports` needs to go from

```
namedExports: {
    'constants/app_constants': [
      'Actions',
    ],
  },
```

to 

```
namedExports: {
    'app/constants/app_constants': [
      'Actions',
    ],
  },
```

This is a little confusing. With 2.0, we're planning to simplify namedExports so that you hopefully won't have to define them at all. Here's a discussion around that feature: https://github.com/Galooshi/import-js/issues/199

**Comment by trotzig** [comment]
I haven't looked too closely at the code, but the title hints that this PR might be two-fold (also fixing #4). If so, would you mind breaking that out into its own PR?

**Comment by z4139jq** [comment]
I have tried importjs-1.1.2, those cases I tried to fix and the one from @kevinkehl are all handled. Thanks.

**Comment by z4139jq** [comment]
@trotzig , my pleasure, So I'm gonna close this PR, and create another one to just fix issue #4.

**Pull request closed without merging**
